const TermsOfUse = () => {
    return (
        <section className="py-10 sm:py-16">
            <div className="px-4 mx-auto sm:px-6 lg:px-8 max-w-7xl">
                <div className="max-w-3xl mx-auto text-center">
                    <h2 className="text-3xl font-bold leading-tight text-transparent bg-clip-text bg-gradient-to-r from-[#dbc7a6] via-[#3d4957] to-[#282e3a] sm:text-4xl lg:text-5xl p-3">
                        Terms Of Use
                    </h2>
                </div>
                <div className="container py-4">
                    <p>Use of this website is for eligible persons only, which includes Retail Clients, Professional Clients and Market Counterparties as defined in 2. Client classification of the Dubai International Financial Center &nbsp;(&ldquo;DIFC&rdquo;) Conduct of Business Rulebook (&ldquo;Eligible Persons&rdquo;).</p><br />
                    <p>Capitalised terms not defined in these Terms of Use shall have the same meaning attributed to them in the relevant Rules of the DIFC.</p><br />
                    <p>Nuqi Digital Wealth Ltd, including but not limited to its shareholders, directors, officers, employees, group members, affiliates, and assignees (collectively referred to as &ldquo;Nuqi&rdquo; or &ldquo;We&rdquo;), accepts no liability and offers no warranties concerning the documentation or information presented on this website, to the fullest extent permitted by law. The information contained on this website is subject to change without notice..</p><br />
                    <p>Nuqi has exercised all reasonable care in compiling the information provided on this website. Nevertheless, Nuqi does not guarantee or assert that the information will be promptly updated or that it will reveal all relevant details regarding the services mentioned herein. Additionally, Nuqi does not verify the authenticity of information obtained from third parties..</p><br />
                    <p>No documentation or information provided on this website is intended to constitute a recommendation of any investment, financial advice, or any other advice by any party in any jurisdiction. Full details on the products and services are not available herein and may be provided by Nuqi upon additional request.</p><br />
                    <p>This website contains general information collected, maintained, and provided for the informative purposes and convenience of the eligible user only and shall not be relied upon to make any final business or investment decisions.</p><br />
                    <p>No information contained on this website should be construed as an investment advertisement. Accordingly, nothing in this website is to be construed as providing financial advice, an offer or invitation made to any person to enter into any legal agreement of any kind or exercise any rights whatsoever, in relation to the offering of any security or a solicitation.</p><br />
                    <p>Unauthorized use of the contents of this website is strictly prohibited. Under no circumstances should the information provided on this website be copied, disseminated, reproduced, or redistributed other than printing or downloading for personal non-commercial use by &lsquo;eligible persons&rsquo; as defined in the DIFC Conduct of Business Rulebook. No rights of any kind are licensed or assigned or shall otherwise pass to persons accessing this website.</p><br />
                    <p>Nuqi does not assume any liability and shall not be liable to you for any damages, including but not limited to, direct or indirect, special, incidental, or consequential damages, losses, or expenses arising in connection with this website and the information contained within, the use of, or the inability to use, the website by any party.</p><br />
                    <p>Any link within this website, except for any link to other Nuqi corporate sites, is included for information purposes only and for your convenience. Nuqi&rsquo;s inclusion of such links does not imply any endorsement of the materials on such links. Nuqi does not accept any liability and shall not be liable to you for any loss or damage arising from or as a result of your acting upon the content of another website to which you may link from this website.</p><br />
                    <p>By proceeding into this website, you are representing and warranting that you are an Eligible Person as defined in the DIFC Conduct of Business Rulebook and agree to the use of the website subject to the terms and conditions stated herein..</p><br />
                    <p>1. Introduction</p><br />
                    <p>Nuqi is a DIFC-based company licensed and regulated by the Dubai Financial Services Authority, is a category 3C firm authorized to carry on regulated activities of managing assets, arranging custody, arranging Credit &amp; Advising on Credit, advising on Financial Products and arranging Deals in Investments, with endorsement of retail and operating an Islamic Window, which is available online and through mobile applications. Nuqi&rsquo;s Dubai Financial Services Authority&rsquo;s reference number is F007613, and the full DFSA Register is available on the DFSA&rsquo;s website which can be accessed here &nbsp;<a data-fr-linked="true" href="https://www.dfsa.ae/public-register/firms/nuqi-digital-wealth-ltd ">https://www.dfsa.ae/public-register/firms/nuqi-digital-wealth-ltd&amp;nbsp</a>;</p><br />
                    <p>1.1 Purpose</p><br />
                    <p>We offer traditional External Assets manager and an automated digital investment management service (the Services). Should you choose to become our client (&ldquo;Client&rdquo;), we will manage a diversified, continually rebalanced portfolio of securities on your behalf in a very low cost and diversified manner.</p><br />
                    <p>When you use our website and mobile application you enter into a series of legally binding agreements. You also agree to our Privacy Policy which covers how we collect, use, share and store your personal information.</p><br />
                    <p>1.2 Binding Agreement</p><br />
                    <p>When you access our website at &nbsp;<a data-fr-linked="true" href="https://uae.nuqiwealth.com/">https://uae.nuqiwealth.com/</a> and/or our mobile application (&quot;our website&quot;, &quot;our App&quot; or &quot;Nuqi&quot;) as a user (&ldquo;User&rdquo;), you&apos;re agreeing to be bound by the following Terms of Use, and, if you&apos;ve elected to become a Client, our Client Agreement. Please therefore take the time to read the following binding Terms of Use below.</p><br />
                    <p>For the purpose of this Terms of Use, a User is an individual who uses our website or App to evaluate our Service, or for educational purposes and a Client is an individual who signs our Client Agreement that entitles the Client to have her or his investment portfolio managed by Nuqi on a discretionary basis and in accordance with an agreed investment mandate. This Terms of Use, as well as the Privacy Policy applies to both Users and Clients.</p><br />
                    <p>If you elect to become a Client, you will be subject to these Terms of Use, our Client Agreement, our Privacy Policy and any additional terms to which you agree when you create and fund an investment account.</p><br />
                    <p><br /></p><br />
                    <p>2. Clients</p><br />
                    <p>2.1 Eligibility</p><br />
                    <p>Nuqi is intended solely for individuals who are 18 years or older. Any access to or use of Nuqi by anyone under 18 is unauthorized, unlicensed, and in violation of these Terms of Use. By accessing or using Nuqi, you represent and warrant that you are 18 or older, that you can form a binding contract with Nuqi, that you are not a person barred from using the Service under the laws of the United Arab Emirates, DIFC laws, or any other applicable jurisdiction, and that you will comply with these Terms of Use Agreement and all applicable local, state, national, and international laws, rules, and regulations..</p><br />
                    <p>You will keep your username and password safe.</p><br />
                    <p>You will not share your account with anyone else.</p><br />
                    <p>2.2 Your Access</p><br />
                    <p>To access certain features of Nuqi, you must register and create a User Account. During registration, you will choose a password, which you will need to access your User Account. Nuqi employs physical, electronic, and procedural safeguards that comply with DIFC standards to protect Users&apos; and Clients&apos; non-public personal information.</p><br />
                    <p>You are responsible for safeguarding your password and User Account information. You agree not to disclose your password to any third party and to notify Nuqi immediately if your password is lost or stolen or if you suspect any unauthorized use of your User Account. As a User, you agree to be solely responsible for any activities or actions under your User Account, whether or not you have authorized such activities or actions.</p><br />
                    <p>You agree that the information you provide during account registration through our website, app, or any other communication channel will be true, accurate, current, and complete.</p><br />
                    <p>You are prohibited from scraping or copying information through any means (including crawlers, browser plugins, add-ons, and any other technology or manual work) as detailed in Section 6.2.</p><br />
                    <p>The content of the site is protected by applicable copyright and trademark laws. Unauthorized use or exploitation of such content is strictly prohibited, including, but not limited to, unauthorized downloading, retransmission, storage in any medium, copying, redistribution, reproduction, or republication of the site, or any part thereof, for any purpose.</p><br />
                    <p>Nuqi cannot guarantee complete confidentiality or security for information that is transmitted electronically. By accessing the site, you acknowledge that Nuqi is not responsible for any damages or losses you may suffer due to your electronic transmission of confidential or sensitive details. Please refer to Nuqi&rsquo;s privacy policy for more information. We may send you communications that you are required to read. You may customize them according to your preferences.</p><br />
                    <p>2.3 Alerts, Notifications and Service Communications</p><br />
                    <p>By creating a User Account, you automatically sign up for various types of alerts via e-mail and mobile notifications. When logged in, you may customize, modify, and in some cases, deactivate alerts by adjusting the settings accordingly.&nbsp;</p><br />
                    <p>We never include your password in these communications; however, we may include your name, email address, and information about your portfolio(s) if you are a Client. Anyone with access to your email or mobile device will be able to view these alerts.</p><br />
                    <p>3. TermsOfUse and Limit of Liability</p><br />
                    <p>Nuqi cannot be held responsible for any financial insights or recommendations provided to Users. This website is only intended to provide you with general information and is neither considered to be a financial advice, an offer to sell nor a solicitation of an offer to purchase any security and may not rely on investment purposes.</p><br />
                    <p>3.1 For a User who is not a Client</p><br />
                    <p>You understand and acknowledge that the investment results you could obtain from investment information and financial insights provided by Nuqi cannot be guaranteed and that Nuqi cannot be held responsible. All investments entail a risk of loss and that you may lose all your money. Investment management services may be offered to individuals who become clients, at the sole discretion of Nuqi. Your election to engage our investment management services are subject to your explicit enrolment and acceptance of the separate Client Agreement and related fee schedule.</p><br />
                    <p>You agree and understand that your use of Nuqi is for its intended purposes only and it is not intended to provide legal, tax or financial planning advice. You agree as a User that you are responsible for your own investment research and investment decisions, that Nuqi is only one of many tools you may use as part of a comprehensive investment education process, that you should not and will not rely on Nuqi as the primary basis of your investment decisions and, except as otherwise provided for herein, Nuqi will not be liable for decisions/ actions you take or authorize third parties to take on your behalf based on information you receive as a User of Nuqi or information you otherwise see on our website.</p><br />
                    <p>Other sites accessed by hyperlinks appearing in the site may be independently developed by parties other than Nuqi. Nuqi does not guarantee the accuracy of the information contained in such sites.</p><br />
                    <p>Links to other sites should not be taken as Nuqi&rsquo;s endorsement or approval of such sites, the third parties named therein, or their products and services, nor is any liability assumed for incompatibility, non-suitability, viral infection or other destructive components on or from such sites.</p><br />
                    <p>This is our TermsOfUse of legal liability.</p><br />
                    <p>3.2 TermsOfUse of Warranties</p><br />
                    <p>Your use of Nuqi&apos;s website, and the personal information you provide is at your sole discretion and risk. Nuqi&apos;s website and all materials, information, products and services included therein, are provided on an AS IS and AS AVAILABLE basis without any representations, warranties or conditions of any kind from Nuqi. Whether expressed or implied, and including without limitation implied representations, warranties or conditions of title, non-infringement, merchantability, fitness for a particular purpose, performance, durability, availability, timeliness, accuracy, or completeness, all of which are now disclaimed by Nuqi to the fullest extent permitted by law.</p><br />
                    <p>NUQI EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, RELATING TO NUQI&apos;S WEBSITE, CONTENT, AND USER INFORMATION, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT OF PROPRIETARY RIGHTS, COURSE OF DEALING, OR COURSE OF PERFORMANCE. NUQI DISCLAIMS ANY WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:</p><br />
                    <p>- THE AVAILABILITY, SECURITY, ACCURACY, RELIABILITY, TIMELINESS, AND PERFORMANCE OF NUQI&apos;S WEBSITE, CONTENT, AND/OR USER INFORMATION.</p><br />
                    <p>- THAT NUQI&apos;S WEBSITE WILL BE ERROR-FREE OR THAT ANY ERRORS WILL BE CORRECTED.</p><br />
                    <p>- THAT NUQI&apos;S WEBSITE WILL BE FREE FROM ELECTRONIC VIRUSES.</p><br />
                    <p>- THE PERFORMANCE OF OR ACCURACY, QUALITY, CURRENCY, COMPLETENESS, OR USEFULNESS OF ANY INFORMATION PROVIDED BY NUQI ON ITS WEBSITE, INCLUDING BUT NOT LIMITED TO INFORMATION OBTAINED THROUGH SOCIAL MEDIA..</p><br />
                    <p>No advice or information, whether oral or written, obtained by you from Nuqi&apos;s website, shall create any warranty not expressly stated in this Terms of Use. If you choose to rely on such information, you do so solely at your own risk.</p><br />
                    <p>Some countries or jurisdictions do not allow the exclusion of certain warranties. Accordingly, some of the above exclusions may not apply to you.</p><br />
                    <p>These are the limits of legal liability we may have to you.</p><br />
                    <p>3.3 Limitation of Liability</p><br />
                    <p>IN NO EVENT SHALL NUQI OR ANY OF ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU FOR ANY DAMAGES WHATSOEVER, INCLUDING WITHOUT LIMITATION INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF NUQI, CONTENT AND/OR USER INFORMATION, INCLUDING BUT NOT LIMITED TO THE QUALITY, ACCURACY, OR UTILITY OF THE INFORMATION PROVIDED AS PART OF OR THROUGH NUQI OR FOR ANY INVESTMENT DECISIONS MADE ON THE BASIS OF SUCH INFORMATION, WHETHER THE DAMAGES ARE FORESEEABLE AND WHETHER OR NOT NUQI HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION AND IN NO EVENT SHALL NUQI&apos;S CUMULATIVE LIABILITY TO YOU EXCEED U.S. AED250.</p><br />
                    <p>Every effort has been made to ensure that the website&apos;s material is accurate at the time of publication. However, Nuqi will not under any circumstances be liable to you or any other person in any way for any loss or damages (direct, indirect, special, economic, incidental, consequential, punitive or exemplary, including without limitation loss of revenue, data, anticipated profits or lost business) in respect of the use of, or inability to use, or any reliance on, the website, any of its content or links (including without limitation any inaccuracies or viruses), or any web browser or other equipment.</p><br />
                    <p>By accessing the website, you agree to indemnify and hold harmless Nuqi and its agents, suppliers and their respective directors, officers, and employees from and against all actions, proceedings, costs, claims, liabilities, damages, and expenses (including reasonable legal fees) arising from or in connection with a breach of these terms and conditions or the use of this website.</p><br />
                    <p>4. Termination</p><br />
                    <p>Each of us can end this Terms of Use at any time.</p><br />
                    <p>You may request termination of your User Account at any time and for any reason by sending an email to <a data-fr-linked="true" href="mailto:service@nuqiwealth.me">service@nuqiwealth.me</a>&nbsp; or through the process specified in the App.</p><br />
                    <p>We may terminate or suspend your access to Nuqi, in our sole discretion, at any time for any reason without notice to you. Further, if we believe, in our sole discretion, that a violation of these Terms of Use has occurred, we may take any other corrective action we deem appropriate. We reserve the right to investigate suspected violations of these Terms of Use. We may seek to gather information from a user who is suspected of violating these Terms of Use (or from any other user) and you agree to provide us with such information. We will fully cooperate with any law enforcement authorities or court order requesting or directing us to disclose the identity of anyone posting, publishing, or otherwise making available any User information, emails, or other materials that are believed to violate these Terms of Use.</p><br />
                    <p>Any suspension, termination, or cancellation shall not affect your obligations to Nuqi under these Terms of Use (including but not limited to ownership, indemnification, and limitation of liability), which by their sense and context are intended to survive such suspension, termination, or cancellation.</p><br />
                    <p>5. Dispute Resolution</p><br />
                    <p>You agree that these Terms of Use shall be governed by and interpreted in accordance with the laws of the DIFC excluding that body of law pertaining to conflict of laws.</p><br />
                    <p>Any legal action or proceeding arising under these Terms of Use will be brought exclusively in courts of the DIFC, and the parties hereby irrevocably consent to the personal jurisdiction and venue therein.</p><br />
                    <p>6. Nuqi &quot;Dos&quot; and &quot;Don&apos;ts&quot;</p><br />
                    <p>Nuqi grants you a license to use our website and App so long as you comply with all our rules.</p><br />
                    <p>6.1 Dos.</p><br />
                    <p>You agree you will:</p><br />
                    <p>Comply with all applicable laws, including, without limitation, privacy laws, intellectual property laws, export control laws, tax laws, and regulatory requirements;</p><br />
                    <p>Provide accurate information to us, whether reported directly or through a third party who you authorize, and keep it updated;</p><br />
                    <p>Use the services solely for your personal, non-commercial use;</p><br />
                    <p>Use your real name on your profile and keep your password confidential; and</p><br />
                    <p>Use the Services in a professional manner.</p><br />
                    <p>6.2 Don&apos;ts.</p><br />
                    <p>You agree you won&apos;t:</p><br />
                    <p>Circumvent, disable, or otherwise interfere with security-related features of Nuqi or features that prevent or restrict use or copying of any content or User information.</p><br />
                    <p>Upload, email, transmit, provide, or otherwise make available:</p><br />
                    <p>any User information which you do not have the lawful right to use, copy, transmit, display, or make available (including any User information that would violate any confidentiality or fiduciary obligations that you might have with respect to the User information); or</p><br />
                    <p>any User information that infringes the intellectual property rights of, or violates the privacy rights of, any third-party (including without limitation copyright, trademark, patent, trade secret, or other intellectual property right, moral right, or right of publicity); or</p><br />
                    <p>unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of solicitation; or</p><br />
                    <p>any personal information that is unlawful, obscene, harmful, threatening, harassing, defamatory, or hateful, or that contain objects or symbols of hate, invade the privacy of any third-party, contain nudity, are deceptive, threatening, abusive, inciting of unlawful action, or are otherwise objectionable in the sole discretion of Nuqi; or</p><br />
                    <p>any personal information that contains software viruses or any other computer code, files, or programs designed to (i) interrupt, destroy, or limit the functionality of any computer software; or (ii) interfere with the access of any user, host or network, including without limitation overloading, flooding, spamming, mail-bombing, or sending a virus to Nuqi; or</p><br />
                    <p>any personal information that includes code that is hidden or otherwise surreptitiously contained within the User information.</p><br />
                    <p>Use any meta tags or other hidden text or metadata utilising a Nuqi name, trademark, URL or product name.</p><br />
                    <p>Forge any TCP/IP packet header or any part of the header information in any posting, or in any way use Nuqi to send altered, deceptive, or false source- identifying information.</p><br />
                    <p>Interfere with or disrupt (or attempt to interfere with or disrupt) any Nuqi web page, server, or network, or the technical delivery systems of Nuqi&apos;s providers, or disobey any requirements, procedures, policies, or regulations of networks connected to Nuqi.</p><br />
                    <p>Attempt to probe, scan, or test the vulnerability of any Nuqi system or network or breach or impair or circumvent any security or authentication measures protecting Nuqi.</p><br />
                    <p>Attempt to decipher, decompile, disassemble, or reverse-engineer any of the software used to provide Nuqi.</p><br />
                    <p>Attempt to access, search, or meta-search Nuqi or content thereon with any engine, software, tool, agent, device, or mechanism other than software and/or search agents provided by Nuqi or other generally available third- party web browsers, including without limitation any software that sends queries to Nuqi to determine how a website or web page ranks.</p><br />
                    <p>Violate the terms of service or any other rule or agreement applicable to you or Nuqi&apos;s inclusion in, reference to, or relationship with any third party or third-party site or service, or your use of any such third-party site or service.</p><br />
                    <p>Collect or store personal information about other users without their express permission.</p><br />
                    <p>Impersonate or misrepresent your affiliation with any person or entity, through pretexting or some other form of social engineering, or commit fraud.</p><br />
                    <p>Solicit any User for any investment or other commercial or promotional transaction.</p><br />
                    <p>Violate any applicable law and regulation.</p><br />
                    <p>Scrape or copy information through any means (including crawlers, browser plugins and add-ons, and any other technology or manual work).</p><br />
                    <p>Use, launch, or permit to be used any automated system, including without limitation &quot;robots,&quot; &quot;crawlers,&quot; or &quot;spiders&quot;; or</p><br />
                    <p>Copy or use the information, content or data on Nuqi in connection with a competitive service (as determined by Nuqi).</p><br />
                    <p>Monitor Nuqi&apos;s availability, performance or functionality for any competitive purposes.</p><br />
                    <p>Use Nuqi or content thereon in any manner not permitted by these Terms of Use</p><br />
                    <p>Copyrighted Materials.</p><br />
                    <p><br /></p><br />
                    <p>If you become aware of any misuse of Nuqi or its content by any person, please contact Nuqi to report the abuse. Nuqi has adopted and implemented a policy that provides for the termination of Accounts of users who infringe the rights of copyright holders.</p><br />
                    <p><br /></p><br />
                    <p>7. Account Information from Third Party Sites</p><br />
                    <p>Users may link their accounts with third-party financial institutions with which they have customer relationships, maintain accounts or engage in financial transactions and direct Nuqi to retrieve and display information from these accounts (&ldquo;Account Information&rdquo;). Nuqi works with one or more third-party service providers to access this Account Information. By linking these accounts or directing Nuqi to retrieve your third-party Account Information, you are consenting to the processing of your Account Information, and other personal information you provide that is needed to retrieve your Account Information, such as credentials, by Nuqi and such service provider(s) in connection with providing this service in accordance with our Privacy Policy and as permitted by law, and, if you&rsquo;ve elected to become a Client, you are consenting to the use of your Account Information by Nuqi and its affiliates in connection with the management of your Nuqi account. Nuqi does not review the Account Information for accuracy, legality or non-infringement. Nuqi is not responsible for the Account Information or products and services offered by or on third-party sites.</p><br />
                    <p>Nuqi cannot always foresee or anticipate technical or other difficulties which may result in failure to obtain data or loss of data, personalization settings or other service interruptions. Nuqi cannot assume responsibility for the timeliness, accuracy, deletion, non-delivery or failure to store any user data, communications or personalization settings. Displayed Account Information is only as fresh as the time shown, which reflects when the information was obtained from third-party sources.</p><br />
                    <p>8. General Terms</p><br />
                    <p>Some other important details about the Terms of Use:</p><br />
                    <p>In the event that any provision in these Terms of Use is held to be invalid or unenforceable, the remaining provisions will remain in full force and effect. The failure of a party to enforce any right or provision of these Terms of Use will not be deemed a waiver of such right or provision. You may not assign this Terms of Use (by operation of law or otherwise) without the prior written consent of Nuqi, and any prohibited assignment will be null and void.</p><br />
                    <p>Nuqi may assign this Terms of Use or any rights hereunder without your consent. The relationship of the parties under these Terms of Use is that of independent contractors, and these Terms of Use will not be construed to imply that either party is the agent, employee, or joint venture of the other. Note that if you elect to become a Client, the relationship of the parties will be governed by these Terms of Use, Client Agreement, our Privacy Policy and any additional terms to which you agree when you create and fund an investment account.</p><br />
                    <p>We may make changes to this Terms of Use and the Service from time to time. We may do this for various reasons, including to reflect changes in or requirements of the applicable law, new features, or changes in business practices.</p><br />
                    <p>The latest version of this Terms of Use will be posted on the website under Terms of Use, and you should regularly check for the latest version. The newest version is the version that applies. If you continue to use the Service after the changes become effective, you agree to the revised Terms of Use. You agree that this Terms of Use shall supersede any prior agreements (except as specifically stated herein) and shall govern your entire relationship with Nuqi, including but not limited to events, agreements, and conduct preceding your acceptance of this Terms of Use. We reserve the right to change this Terms of Use by posting a revised Terms of Use and we agree that changes cannot be retroactive. If you don&apos;t agree with these changes, you must stop using Nuqi.</p><br />
                    <p>You agree the only way to provide us legal notice is at the address provided in Section 10.3.</p><br />
                    <p>9. International Use</p><br />
                    <p>Nuqi does not make any representation that its services are appropriate or available for use outside the DIFC. Similarly, we make no representations that accessing Nuqi from locations outside the DIFC is legal or permissible under local laws. If you access Nuqi from areas outside of the DIFC, you do so at your own risk and are solely responsible for compliance with local laws.</p><br />
                    <p>10. Miscellaneous</p><br />
                    <p>10.1 Integration &amp; Severability</p><br />
                    <p>This Terms of Use is the entire agreement between you and us with respect to Nuqi, and your use of our website and App, and supersedes all prior or contemporaneous communications and proposals (whether oral, written or electronic) between you and us. If any provision of this Terms of Use is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Terms of Use will otherwise remain in full force and effect. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder.</p><br />
                    <p>Investment recommendations are made to Clients on an individual basis and may differ based on specific circumstances.</p><br />
                    <p>10.2 Advice may differ</p><br />
                    <p>We and our personnel may make recommendations and take action for Clients that may differ from the recommendations we give to you or the action we take on your behalf.</p><br />
                    <p>In addition, our personnel may take actions for their own accounts based on their own investment situations that differ from the recommendations we give you or actions we take on your behalf.</p><br />
                    <p>Any notice or communication will be in writing by email.</p><br />
                    <p>10.3 Communication</p><br />
                    <p>You agree that these Terms of Use and the rules, restrictions, and policies contained herein, and Nuqi&apos;s enforcement thereof, are not intended to confer and do not confer any rights or remedies on any person other than you and Nuqi. These Terms of Use together with Nuqi&apos;s Privacy Policy and Client Agreement (if applicable) constitute the entire agreement between Nuqi and you with respect to the subject matter hereof. Any notice or other communication to be given hereunder will be in writing and given by (a) Nuqi via email (in each case to the address that you provide), or (b) you via email to <a data-fr-linked="true" href="mailto:service@nuqiwealth.me">service@nuqiwealth.me</a> or to such other addresses as Nuqi may specify in writing. The date of receipt shall be deemed the date on which such notice is transmitted.</p><br />
                    <p>We welcome your feedback!</p><br />
                    <p>10.4 Feedback</p><br />
                    <p>Your feedback is welcome and encouraged. You may submit feedback by emailing us at <a data-fr-linked="true" href="mailto:service@nuqiwealth.me">service@nuqiwealth.me</a> . You agree, however, that (i) by submitting unsolicited ideas to Nuqi or any of its employees or representatives, by any medium, including but not limited to email, written, or oral communication, you automatically forfeit your right to any intellectual property rights in such ideas; and (ii) such unsolicited ideas automatically become the property of Nuqi. You hereby assign and agree to assign all rights, title, and interest you have in such feedback and ideas to Nuqi together with all intellectual property rights therein. In addition, you warrant that all moral rights in any feedback have been waived, and you do hereby waive any such moral rights.</p><br />
                    <p>10.5 Questions</p><br />
                    <p>This document constitutes Nuqi&apos;s complete Terms of Use for Nuqi and related services.</p><br />
                    <p>If you have questions about these Terms of Use or about Nuqi or content thereon, please contact Nuqi at <a data-fr-linked="true" href="mailto:service@nuqiwealth.me">service@nuqiwealth.me</a> .</p><br />
                    <p>11. Severance</p><br />
                    <p>No consent or waiver by either party, or of any breach or default by, the other party in its performance of its obligations under this Terms of Use will be deemed or construed to be a consent to, or a waiver of, a continuing breach or default or any other breach or default of those or any other obligations of that party. No consent or waiver will be effective unless in writing.</p><br />
                    <p>If any provision of these terms and conditions is unlawful, void, or for any reason is unenforceable. That provision shall be deemed to be severed from the rest of these terms and conditions and shall not affect the validity and enforceability of any remaining provisions.</p><br />
                </div>
            </div>
        </section>
    );
};

export default TermsOfUse;
